<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { apiGet, apiPost } from '@/api/client'

interface Skill { skill_id: string; name: string; description: string; content_hash: string; status: string }
function message(error: unknown): string { return error instanceof Error ? error.message : String(error) }
const skills = ref<Skill[]>([]); const name = ref(''); const description = ref(''); const purpose = ref(''); const instructions = ref<string[]>(['']); const examples = ref<string[]>([]); const knowledgeRefs = ref(''); const roles = ref(''); const priority = ref(100); const maxTokens = ref(4096); const required = ref(true); const conflictTags = ref(''); const creating = ref(false); const error = ref(''); const validation = ref<{ valid: boolean; message?: string } | null>(null)
const body = computed(() => ({ purpose: purpose.value.trim(), instructions: instructions.value.map(v => v.trim()).filter(Boolean), examples: examples.value.map(v => v.trim()).filter(Boolean), knowledge_refs: knowledgeRefs.value.split(/\n/).map(v => v.trim()).filter(Boolean).map(artifact_version_id => ({ artifact_version_id })), applicable_agent_roles: roles.value.split(',').map(v => v.trim()).filter(Boolean), priority: Number(priority.value), conflict_tags: conflictTags.value.split(',').map(v => v.trim()).filter(Boolean), max_assembly_tokens: Number(maxTokens.value), assembly_policy: { required: required.value, max_tokens: Number(maxTokens.value) } }))
onMounted(load)
async function load() { try { skills.value = await apiGet<Skill[]>('/skills') } catch { skills.value = [] } }
function add(list: string[]) { list.push('') } function remove(list: string[], index: number) { list.splice(index, 1) }
async function validate() { try { validation.value = await apiPost('/skills/validate', { body: body.value }) as { valid:boolean } } catch (e) { validation.value = { valid:false, message:message(e) } } }
async function create() { if (!name.value.trim()) return; creating.value = true; try { await apiPost('/skills', { name:name.value, description:description.value, body:body.value }); name.value=''; description.value=''; await load() } catch (e) { error.value=message(e) } finally { creating.value=false } }
</script>
<template>
  <main class="skill-page"><header><h1>Skill Workshop</h1><p>Skill 是不可执行的版本化指令与知识；不包含工具、网络或凭证。</p></header><p v-if="error" class="error">{{ error }}</p>
    <form class="create" @submit.prevent="create"><input v-model="name" placeholder="Skill 名称" required><input v-model="description" placeholder="描述"><button :disabled="creating">{{ creating ? '创建中...' : '保存 Skill 草稿' }}</button></form>
    <section class="editor"><fieldset><legend>概览与适用范围</legend><label>用途<input v-model="purpose" placeholder="例如：长篇小说世界观一致性检查"></label><label>适用 Agent 角色（逗号分隔）<input v-model="roles" placeholder="writer, reviewer"></label></fieldset><fieldset><legend>指令</legend><div v-for="(_item,index) in instructions" :key="index" class="line"><input v-model="instructions[index]" placeholder="一条不可执行的写作/审核指令"><button type="button" :disabled="instructions.length === 1" title="删除指令" @click="remove(instructions,index)">×</button></div><button type="button" @click="add(instructions)">添加指令</button></fieldset><fieldset><legend>示例</legend><div v-for="(_item,index) in examples" :key="index" class="line"><textarea v-model="examples[index]" rows="2" placeholder="示例（不包含私密数据）"></textarea><button type="button" title="删除示例" @click="remove(examples,index)">×</button></div><button type="button" @click="add(examples)">添加示例</button></fieldset><fieldset><legend>只读知识</legend><label>ArtifactVersion IDs（每行一个，同 owner 的固定版本）<textarea v-model="knowledgeRefs" rows="3" placeholder="ArtifactVersion UUID"></textarea></label></fieldset><fieldset><legend>预算与冲突</legend><div class="grid"><label>优先级<input v-model.number="priority" type="number" min="0"></label><label>最大装配 token<input v-model.number="maxTokens" type="number" min="1"></label></div><label>冲突标签（逗号分隔；!格式表示相反规则）<input v-model="conflictTags"></label><label class="check"><input v-model="required" type="checkbox"> 必需 Skill：超预算/撤权时阻断编译</label></fieldset></section>
    <div class="actions"><button @click="validate">预览装配与安全校验</button><button class="primary" @click="create">保存 Skill 草稿</button></div><p v-if="validation" :class="validation.valid ? 'result':'error'">{{ validation.valid ? '校验通过：可提交固定修订并供 Agent 装配' : validation.message }}</p><section class="list"><article v-for="skill in skills" :key="skill.skill_id"><strong>{{ skill.name }}</strong><span>{{ skill.status }}</span><code>{{ skill.content_hash?.slice(0,12) }}</code></article></section></main>
</template>
<style scoped>
.skill-page{max-width:960px;margin:auto;padding:24px;color:var(--text-primary)} header p{color:var(--text-secondary)} input,textarea,button{box-sizing:border-box;font:inherit} input,textarea{width:100%;padding:8px;color:var(--text-primary);background:var(--bg-primary);border:1px solid var(--border);border-radius:4px} button{padding:7px 12px;border:1px solid var(--border);border-radius:4px;background:var(--bg-primary);color:var(--text-primary);cursor:pointer}.create,.actions,.grid,.line{display:flex;gap:8px;align-items:center}.create input{flex:1}.editor{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}fieldset{min-width:0;border:1px solid var(--border);border-radius:5px;padding:12px}label{display:block;font-size:13px;margin-bottom:8px}.line{margin-bottom:7px}.line input,.line textarea{flex:1}.check{display:flex;gap:8px;align-items:center}.check input{width:auto}.actions{margin-top:12px}.primary,.create button{background:var(--accent);color:white}.result,.error{margin-top:12px;padding:8px;border-radius:4px;background:var(--bg-secondary)}.error{color:#b91c1c;background:#fef2f2}.list{display:grid;gap:5px;margin-top:16px}.list article{display:flex;gap:10px;padding:8px;border:1px solid var(--border);border-radius:4px}.list span{color:var(--text-secondary)}@media(max-width:680px){.editor{grid-template-columns:1fr}.create{flex-wrap:wrap}}
</style>
