"""Foundation schema

Revision ID: 471fc0c910c9
Revises: 
Create Date: 2026-07-12 15:38:03.452866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471fc0c910c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_scope', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETION_PENDING', 'DELETED_TOMBSTONE', name='projectstatus'), nullable=False),
    sa.Column('default_entry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('user_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETION_PENDING', 'DELETED_TOMBSTONE', name='accountstatus'), nullable=False),
    sa.Column('owner_scope', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workflows',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('owner_scope', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('workflow_drafts',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('base_revision_id', sa.UUID(), nullable=True),
    sa.Column('graph', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('graph_hash', sa.String(length=64), nullable=True),
    sa.Column('layout_hash', sa.String(length=64), nullable=True),
    sa.Column('execution_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('workflow_revisions',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('graph_hash', sa.String(length=64), nullable=False),
    sa.Column('execution_hash', sa.String(length=64), nullable=False),
    sa.Column('registry_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('revision_status', sa.Enum('DRAFT', 'ACTIVE', 'RETIRED', name='revisionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_revision_id', sa.UUID(), nullable=False),
    sa.Column('compiled_plan_id', sa.UUID(), nullable=False),
    sa.Column('owner_scope', sa.String(length=255), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'WAITING_USER', 'CANCELLING', 'CANCELLED', 'COMPLETED', 'FAILED', name='runstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_revision_id'], ['workflow_revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('node_runs',
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_instance_id', sa.String(length=255), nullable=False),
    sa.Column('node_type_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('node_run_id')
    )
    op.create_table('node_run_attempts',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('node_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('execution_epoch', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'LEASED', 'RUNNING', 'WAITING_EXTERNAL', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUPERSEDED', 'UNKNOWN', name='attemptstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_run_id'], ['node_runs.node_run_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_run_attempts')
    op.drop_table('node_runs')
    op.drop_table('workflow_runs')
    op.drop_table('workflow_revisions')
    op.drop_table('workflow_drafts')
    op.drop_table('workflows')
    op.drop_table('user_accounts')
    op.drop_table('projects')
    op.drop_table('outbox_events')
    op.execute("DROP TYPE IF EXISTS accountstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS projectstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS revisionstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS runstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS attemptstatus CASCADE")
    # ### end Alembic commands ###
